import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>🍀</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link
            rel="preconnect"
            href="https://fonts.gstatic.com"
            crossOrigin="true"
          />
          <link
            href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,400;1,600;1,700&display=swap"
            rel="stylesheet"
          />
      </Head>

      <info className={styles.info}> 
        <h1 className={styles.title}><i>🍀 clover 🍀</i></h1>
        <p className={styles.description}>coming soon</p>
        <p className={styles.description}>ig: <a target='_blank' href='https://www.instagram.com/cloverband_/'>@cloverband_</a></p>
      </info>

      <background className={styles.background}> 
        <video className={styles.video} loop muted playsInline autoPlay> 
          <source src="/2pKXeK.mp4" type="video/mp4"/>
        </video>
      </background>
    </div>
  )
}
